music/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    
    #/music/
    url(r'^$', views.index, name="index"),
    
    #/music/123/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="details"),
    
    #/music/< album id >/favorite
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name="favorite")
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('music.urls')),
    url(r'^music/', include("music.urls")),
    url(r'^admin/', admin.site.urls),
]

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.album_title + ' - ' + self.artist
    
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.song_title

music/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


# Create your views here.

def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums':all_albums}
    return render(request, 'music/index.html', context)

def detail(request, album_id):
	album = get_object_or_404(Album, id=album_id)
	return render(request, 'music/details.html', {'album':album})


def favorite(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    try:
        select_song = album.song_set.get(id=request.POST["song"])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/details.html', {
                "album":album,
                "error_message": "You did not select any song",
                                                      })
    else:
        select_song.is_favorite = True
        select_song.save()
        return render(request, 'music/detail.html', {"album":album})
    

music/templates/music/details.html
<h1>Album Title : {{ album.album_title }}</h1>
<h4>Artist Name : {{ album.artist }}</h4>

{% if error_message %}
    <p><strong>{{ error_message }}<strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" methon="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="">
            {% endif %}
        </label><br />
    {% endfor %}
    
    <input type="submit" name="Favorite" value="Favorite">



</form>

music/templates/music/index.html
<!--- Load the path to your static files -->
{% load staticfiles %}
<link rel="stylesheet" type="test/css" href="{% static 'music/style.css' %}" />

{% if all_albums %}

    <h3> Here are all my Albums</h3>
        
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:details' album.id %}"> {{ album.album_title }} </a></li>
        {% endfor %}
    </ul>   

{% endif %}